CREATE TABLE orders
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id BIGINT                                  NOT NULL,
    food_id   BIGINT                                  NOT NULL,
    quantity  INTEGER                                 NOT NULL,
    toGo      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_FOOD FOREIGN KEY (food_id) REFERENCES foods (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);