quarkus.application.name=restaurant-api

# Configuration for postgreSQL database
quarkus.datasource.username=postgres
quarkus.datasource.password=maria17
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/restaurant_db
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.jdbc.telemetry.enabled=true
quarkus.datasource.jdbc.telemetry=true

# Configuration for flyway
quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true
#quarkus.flyway.clean-at-start=true
#quarkus.flyway.baseline-on-migrate=true
#quarkus.flyway.validate-at-start=true

quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics

quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317

# Configuration OpenTelemetry for send metrics to Collector
quarkus.micrometer.export.otlp.enabled=true
quarkus.micrometer.export.otlp.url=http://localhost:55681/v1/metrics
quarkus.micrometer.export.otlp.step=30s
quarkus.micrometer.export.otlp.batch-size=100

quarkus.hibernate-orm.validate-in-dev-mode=true

# Configuration for kafka
kafka.bootstrap.servers=localhost:9092
kafka.producer.retries=3

quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId} [%c{2.}] %s%e%n

quarkus.http.host=0.0.0.0

quarkus.rest-client.ticket-service-api.url=http://localhost:8082/