CREATE TABLE waiters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    lastname VARCHAR(100),
    phone_number VARCHAR(10),
    CONSTRAINT pk_waiters PRIMARY KEY (id)
);

CREATE TABLE foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    proportion VARCHAR(20) NOT NULL,
    price DOUBLE PRECISION,
    CONSTRAINT pk_foods PRIMARY KEY (id),
    CONSTRAINT uc_foods_name_proportion UNIQUE (name, proportion)
);

CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isPaid BOOLEAN NOT NULL,
    waiter_id BIGINT NOT NULL,
    CONSTRAINT pk_tickets PRIMARY KEY (id),
    CONSTRAINT fk_tickets_waiter FOREIGN KEY (waiter_id) REFERENCES waiters (id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id BIGINT NOT NULL,
    food_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    toGo BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_food FOREIGN KEY (food_id) REFERENCES foods (id),
    CONSTRAINT fk_orders_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);
